export const mockAbbrevCurrencies = [
  {
    "symbol": "BTC",
    "price": 3586.16,
    "percent_change": 0.83,
    "name": "Bitcoin",
    "rank": "1",
  },
  {
    "symbol": "XRP",
    "price": 0.33,
    "percent_change": 3.94,
    "name": "XRP",
    "rank": "2",
  },
  {
    "symbol": "ETH",
    "price": 95.07,
    "percent_change": 0.20,
    "name": "Ethereum",
    "rank": "3",
  },
  {
    "symbol": "EOS",
    "price": 2.54,
    "percent_change": 6.87,
    "name": "EOS",
    "rank": "4",
  },
  {
    "symbol": "XLM",
    "price": 0.11,
    "percent_change": -0.58,
    "name": "Stellar",
    "rank": "5",
  },
  {
    "symbol": "USDT",
    "price": 1.02,
    "percent_change": -0.37,
    "name": "Tether",
    "rank": "6",
  },
  {
    "symbol": "BCH",
    "price": 100.65,
    "percent_change": 12.32,
    "name": "Bitcoin Cash",
    "rank": "7",
  },
  {
    "symbol": "LTC",
    "price": 28.99,
    "percent_change": -1.97,
    "name": "Litecoin",
    "rank": "8",
  },
  {
    "symbol": "BSV",
    "price": 81.84,
    "percent_change": -1.04,
    "name": "Bitcoin SV",
    "rank": "9",
  },
  {
    "symbol": "TRX",
    "price": 0.01,
    "percent_change": 0.17,
    "name": "TRON",
    "rank": "10",
  }
]